default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: microcommerce_development

test:
  <<: *default
  database: microcommerce_test

production:
  <<: *default
  database: microcommerce_production
  username: microcommerce
  password: <%= ENV['MICROCOMMERCE_DATABASE_PASSWORD'] %>
